BANKS = {}

BANKS['game-cmdline-gauntlet'] = {
 "kind": "input", "intro": "Type the command that achieves the goal. Common variations accepted.",
 "challenges": [
  {"q": "Find every file owned by user bob under the current directory.",
   "answers": ["find . -user bob", "find . -user bob ", "find ./ -user bob"],
   "hint": "find with an owner filter"},
  {"q": "Show the last 20 lines of /var/log/auth.log and follow new lines.",
   "answers": ["tail -f -n 20 /var/log/auth.log", "tail -fn20 /var/log/auth.log", "tail -n 20 -f /var/log/auth.log", "tail -f -20 /var/log/auth.log"],
   "hint": "tail with a follow flag"},
  {"q": "Find all setuid binaries on the system.",
   "answers": ["find / -perm -4000 2>/dev/null", "find / -perm -4000 -type f 2>/dev/null", "find / -perm -u+s 2>/dev/null", "find / -perm -4000"],
   "hint": "The setuid bit is 4000"},
  {"q": "Search recursively, case insensitive, for the word password in /etc.",
   "answers": ["grep -ri password /etc", "grep -r -i password /etc", "grep -i -r password /etc", "grep -R -i password /etc"],
   "hint": "Recursive plus ignore case"},
  {"q": "List listening TCP ports with the owning process.",
   "answers": ["ss -tlnp", "ss -ltnp", "netstat -tlnp", "netstat -ltnp", "ss -tulpn"],
   "hint": "ss or netstat with listen and process flags"},
  {"q": "Show the environment of running process 1337.",
   "answers": ["cat /proc/1337/environ", "tr '\\0' '\\n' < /proc/1337/environ", "strings /proc/1337/environ"],
   "hint": "Everything is a file"},
  {"q": "Give ONLY the owner read and write, everyone else read: set the mode on file.txt.",
   "answers": ["chmod 644 file.txt", "chmod 0644 file.txt"],
   "hint": "6 then 4 then 4"},
  {"q": "Make script.sh executable by everyone.",
   "answers": ["chmod +x script.sh", "chmod 755 script.sh", "chmod a+x script.sh"],
   "hint": "Add execute"},
  {"q": "Count how many lines in access.log contain the word ERROR.",
   "answers": ["grep -c ERROR access.log", "grep ERROR access.log | wc -l", "grep -c 'ERROR' access.log"],
   "hint": "grep can count"},
  {"q": "Kill process 4242 immediately without cleanup.",
   "answers": ["kill -9 4242", "kill -KILL 4242", "kill -SIGKILL 4242"],
   "hint": "Signal nine"},
  {"q": "Show which commands you are permitted to run with sudo.",
   "answers": ["sudo -l", "sudo --list"],
   "hint": "List"},
  {"q": "Extract the third colon-separated field from every line of /etc/passwd.",
   "answers": ["cut -d: -f3 /etc/passwd", "awk -F: '{print $3}' /etc/passwd", "cut -d : -f 3 /etc/passwd"],
   "hint": "cut with a delimiter, or awk"},
 ],
}

BANKS['game-privesc-path'] = {
 "kind": "builder",
 "intro": "You have an enumeration dump. Choose the escalation path that actually works.",
 "challenges": [
  {"q": "sudo -l shows: (root) NOPASSWD: /usr/bin/vim. What is the path?",
   "items": ["Run vim and execute a shell from inside it with :!/bin/bash", "Edit /etc/passwd directly as the current user", "Use sudo su", "Crack the root password"],
   "correct": 0,
   "why": "vim as root lets you spawn a shell or edit any file. Any editor or interpreter in a NOPASSWD list is game over."},
  {"q": "You find a setuid binary /usr/local/bin/backup that runs `tar czf /backups/x.tar.gz *` in /opt/data. What is the path?",
   "items": ["Wildcard injection: create a file named --checkpoint-action=exec=/bin/bash", "Brute force the service", "Kernel exploit", "Read /etc/shadow directly"],
   "correct": 0,
   "why": "tar with a wildcard expands to filenames, and a filename starting with dashes is parsed as a tar option."},
  {"q": "A root cron job runs `/opt/scripts/cleanup.sh` every minute. /opt/scripts is world-writable. Path?",
   "items": ["Edit cleanup.sh to add a reverse shell and wait a minute", "Kernel exploit", "ARP spoofing", "Brute force SSH"],
   "correct": 0,
   "why": "A writable script run by root on a schedule is a direct escalation. Simplest possible win."},
  {"q": "A root cron runs `backup` with no absolute path and /home/bob/bin is earlier in PATH than /usr/bin, and you can write to /home/bob/bin. Path?",
   "items": ["Create /home/bob/bin/backup as a script that copies /bin/bash with setuid", "Overwrite /usr/bin/backup", "Change the crontab", "Nothing works"],
   "correct": 0,
   "why": "A bare command name resolves through PATH, so a writable earlier directory wins."},
  {"q": "You find credentials for a database in /var/www/app/config.php and the same password works for a local user in /etc/passwd. Path?",
   "items": ["su to that user and check sudo -l again", "Immediately kernel exploit", "Delete the database", "Nothing further"],
   "correct": 0,
   "why": "Password reuse is a lateral move, and the new user may have different sudo rights. Enumeration continues."},
 ],
}

BANKS['game-log-whodunit'] = {
 "kind": "quiz",
 "intro": "A breach left traces. Read the logs and name the technique.",
 "challenges": [
  {"q": "auth.log shows 4,000 failed passwords for root from one IP, then one success. What happened?",
   "a": ["Noise", "Successful brute force against root", "Disk corruption", "Legitimate admin activity"],
   "c": 1, "why": "The burst then success pattern is the signature of guessing until one worked."},
  {"q": "Thousands of DNS queries to random subdomains of one domain, each long, all from one host. What is it?",
   "a": ["Misconfiguration", "DNS tunnelling for data exfiltration", "DDoS", "Normal resolution"],
   "c": 1, "why": "Long random subdomain queries at volume encode data in the query itself."},
  {"q": "A new systemd service file appears in /etc/systemd/system pointing at /tmp/.hidden/x. What is this?",
   "a": ["An update", "Persistence via a malicious service", "A logging change", "Normal admin work"],
   "c": 1, "why": "Executing from a hidden temp path and registered to start on boot is persistence."},
  {"q": "An account with UID 0 appears in /etc/passwd that was not there yesterday. Signigifance?",
   "a": ["Nothing", "A backdoor root account for persistence", "A service account", "A typo"],
   "c": 1, "why": "UID 0 is root. A second root account is a backdoor."},
  {"q": "A user who never used sudo before runs sudo -l followed by sudo cat /etc/shadow. What do you conclude?",
   "a": ["Normal admin", "Possible escalation activity", "Backup job", "Password change"],
   "c": 1, "why": "Enumerating permissions then immediately reading hashes is textbook post-exploitation."},
  {"q": "journalctl shows a process started from /dev/shm. Why is that suspicious?",
   "a": ["It is slow", "Shared memory is memory-backed and leaves less on disk, a common malware location", "It is encrypted", "It is a normal path for services"],
   "c": 1, "why": "/dev/shm is often writable and executable and is a favourite drop location."},
  {"q": "auth.log shows a successful login at 03:14 from a country the employee has never been to, same account used at 09:00 from the office normally. Assessment?",
   "a": ["VPN", "Possible credential compromise, impossible travel", "Clock skew", "Backup login"],
   "c": 1, "why": "Impossible travel between locations in a short window suggests stolen credentials."},
  {"q": "A cron job was added under /var/spool/cron/crontabs for the www-data user. Significance?",
   "a": ["Nothing", "Web server user scheduling tasks suggests web shell persistence", "Backup", "Cleanup job"],
   "c": 1, "why": "www-data should not be scheduling anything; this is persistence after a web compromise."},
 ],
}
