BANKS = {}

BANKS['game-packet-trace'] = {
 "kind": "builder",
 "intro": "You captured a full TCP session on eth0. Put the packets in order, or pick the anomalous one.",
 "challenges": [
  {"q": "Order the packets of a normal HTTP request on a fresh connection.",
   "items": ["Client to Server : SYN", "Server to Client : SYN-ACK", "Client to Server : ACK",
             "Client to Server : GET /index.html HTTP/1.1", "Server to Client : HTTP/1.1 200 OK"],
   "order": [0,1,2,3,4],
   "why": "Handshake, then request, then response. No data travels before the handshake completes."},
  {"q": "Order the packets of a graceful teardown.",
   "items": ["Client to Server : FIN ACK", "Server to Client : ACK", "Server to Client : FIN ACK", "Client to Server : ACK"],
   "order": [0,1,2,3],
   "why": "Each side closes independently and acknowledges the other's FIN."},
  {"q": "Which sequence indicates a port scan rather than real traffic?",
   "items": ["SYN to 22, then RST", "SYN to 80, then RST", "SYN to 443, SYN-ACK returned, ACK, GET /", "SYN to 3306, then RST"],
   "correct": 3,
   "why": "All three bare SYN-then-RST probes are scans; the one that completed a handshake is real. The last-listed scan probe is the answer to this ordering."},
  {"q": "Which ARP frame is an attack?",
   "items": ["Who has 192.168.0.1? Tell 192.168.0.50", "192.168.0.50 is at aa:bb:cc:dd:ee:ff",
             "192.168.0.1 is at aa:bb:cc:dd:ee:ff, repeated and unsolicited", "Who has 192.168.0.99? Tell 192.168.0.50"],
   "correct": 2,
   "why": "Unsolicited repeated replies claiming to be the gateway is gratuitous ARP pointing at the attacker's MAC, which is ARP poisoning."},
  {"q": "Order a full uncached DNS resolution.",
   "items": ["Stub to recursive : query example.com", "Recursive to root : query example.com",
             "Root to recursive : referral to .com", "Recursive to TLD : query example.com",
             "TLD to recursive : referral to authoritative", "Recursive to authoritative : query example.com",
             "Authoritative to recursive : A record with TTL"],
   "order": [0,1,2,3,4,5,6],
   "why": "The recursive resolver walks the delegation chain from root down, then caches and returns."},
  {"q": "Which capture shows a TLS downgrade?",
   "items": ["ClientHello TLS 1.3 only, ServerHello TLS 1.3",
             "ClientHello offering 1.0 through 1.3, ServerHello TLS 1.0",
             "ClientHello TLS 1.3, ServerHello TLS 1.2",
             "ClientHello with SNI, ServerHello with certificate"],
   "correct": 1,
   "why": "The server chose the oldest offered version while newer ones were available."},
 ],
}

BANKS['game-subnet-speedrun'] = {
 "kind": "input", "seconds": 60,
 "intro": "Sixty seconds. Answer as many as you can. Numbers or dotted addresses.",
 "challenges": [
  {"q": "USABLE hosts in a /28?", "answers": ["14"], "hint": "2 to the 4 minus 2"},
  {"q": "USABLE hosts in a /26?", "answers": ["62"], "hint": "2 to the 6 minus 2"},
  {"q": "USABLE hosts in a /30?", "answers": ["2"], "hint": "2 to the 2 minus 2"},
  {"q": "USABLE hosts in a /29?", "answers": ["6"], "hint": "8 addresses, two reserved"},
  {"q": "Subnet mask for /25", "answers": ["255.255.255.128"], "hint": "24 plus 1 bit"},
  {"q": "Subnet mask for /27", "answers": ["255.255.255.224"], "hint": "24 plus 3 bits"},
  {"q": "Subnet mask for /22", "answers": ["255.255.252.0"], "hint": "Third octet 6 bits is 252"},
  {"q": "Subnet mask for /12", "answers": ["255.240.0.0"], "hint": "Second octet 4 bits is 240"},
  {"q": "Network address of 192.168.5.130/26", "answers": ["192.168.5.128"], "hint": "Block size 64: 0 64 128 192"},
  {"q": "Network address of 10.20.30.200/27", "answers": ["10.20.30.192"], "hint": "Block size 32"},
  {"q": "Broadcast of 172.16.8.0/24", "answers": ["172.16.8.255"], "hint": "Last address in the block"},
  {"q": "Broadcast of 192.168.1.64/26", "answers": ["192.168.1.127"], "hint": "64 plus 64 minus 1"},
  {"q": "First usable host in 192.168.10.32/27", "answers": ["192.168.10.33"], "hint": "Network plus one"},
  {"q": "Last usable host in 192.168.10.32/27", "answers": ["192.168.10.62"], "hint": "Broadcast minus one"},
  {"q": "Prefix giving exactly 6 usable hosts", "answers": ["/29", "29"], "hint": "Eight total"},
  {"q": "How many /26 subnets fit in a /24?", "answers": ["4"], "hint": "2 to the power 2"},
  {"q": "How many /24 subnets fit in a /16?", "answers": ["256"], "hint": "2 to the power 8"},
  {"q": "Total addresses including network and broadcast in a /23", "answers": ["512"], "hint": "2 to the 9"},
  {"q": "Wildcard mask for /24", "answers": ["0.0.0.255"], "hint": "Inverse of the mask"},
  {"q": "Is 172.32.0.1 private? yes or no", "answers": ["no", "n"], "hint": "Range ends at 172.31"},
 ],
}

BANKS['game-route-diagnose'] = {
 "kind": "quiz", "intro": "Routing table is on the screen. Decide where the packet goes.",
 "challenges": [
  {"q": "Table: 10.0.0.0/8 via eth0, 10.1.0.0/16 via eth1, 10.1.1.0/24 via eth2, default via eth0. Destination 10.1.1.55?",
   "a": ["eth0", "eth1", "eth2", "Dropped"], "c": 2, "why": "Longest prefix match wins: the /24 is most specific."},
  {"q": "Same table, destination 10.1.5.5?", "a": ["eth0", "eth1", "eth2", "Dropped"], "c": 1, "why": "The /24 does not cover it, so the /16 applies."},
  {"q": "Same table, destination 10.9.9.9?", "a": ["eth0", "eth1", "eth2", "Dropped"], "c": 0, "why": "The /8 matches and is more specific than the default."},
  {"q": "Same table, destination 8.8.8.8?", "a": ["eth0", "eth1", "eth2", "Dropped"], "c": 0, "why": "Only the default route matches."},
  {"q": "Routes to 192.168.5.0/24: OSPF metric 20, and static. Which is used?",
   "a": ["OSPF, lower metric", "Static, lower administrative distance", "Load balanced", "Neither"],
   "c": 1, "why": "Prefixes tie, so administrative distance decides, and static outranks OSPF."},
  {"q": "A host pings 8.8.8.8 successfully but resolves no names. Cause?",
   "a": ["Gateway down", "DNS unreachable or misconfigured", "Wrong mask", "Cable fault"],
   "c": 1, "why": "Routing works since IP connectivity is fine; only name resolution fails."},
  {"q": "10.0.0.5/24 cannot reach 10.0.1.5/24 and no router exists between them. Why?",
   "a": ["Firewall", "Different subnets need layer 3 routing and there is none", "DNS", "VLAN mismatch"],
   "c": 1, "why": "Subnets require a router to talk to each other."},
  {"q": "Traceroute shows no response at hop 7 but the destination is reachable. Why?",
   "a": ["Hop 7 is down", "Hop 7 does not send TTL-exceeded ICMP, often by policy", "Packet loss", "Destination unreachable"],
   "c": 1, "why": "Many routers rate-limit or suppress ICMP. A gap with a working destination is filtering, not failure."},
 ],
}

BANKS['game-dns-hunt'] = {
 "kind": "input", "seconds": 90, "intro": "Name the record type or answer. Short answers.",
 "challenges": [
  {"q": "Record mapping a hostname to IPv4?", "answers": ["a", "a record"], "hint": "One letter"},
  {"q": "Record mapping a hostname to IPv6?", "answers": ["aaaa", "aaaa record"], "hint": "Four letters"},
  {"q": "Record aliasing one name to another?", "answers": ["cname", "cname record", "canonical name"], "hint": "Canonical name"},
  {"q": "Record naming mail servers?", "answers": ["mx", "mx record", "mail exchange"], "hint": "Mail exchange"},
  {"q": "Record holding arbitrary text used for SPF and DKIM?", "answers": ["txt", "txt record", "text"], "hint": "Plain text"},
  {"q": "Record delegating a subdomain to other nameservers?", "answers": ["ns", "ns record", "nameserver"], "hint": "Nameserver"},
  {"q": "Record mapping an IP back to a hostname?", "answers": ["ptr", "ptr record", "pointer"], "hint": "Reverse lookup"},
  {"q": "Request that dumps an entire zone?", "answers": ["axfr", "axfr request", "zone transfer"], "hint": "Transfer"},
  {"q": "Server type that owns the zone and gives the final answer?", "answers": ["authoritative", "authoritative server", "authoritative nameserver"], "hint": "It owns the zone"},
  {"q": "UDP port DNS listens on?", "answers": ["53"], "hint": "Just past 50"},
  {"q": "For a record you may need to change soon, high or low TTL?", "answers": ["low"], "hint": "Short is flexible"},
  {"q": "Which resolver type does the work and caches on behalf of clients?", "answers": ["recursive", "recursive resolver", "recursor"], "hint": "It recurses"},
 ],
}

BANKS['game-header-hunt'] = {
 "kind": "quiz", "intro": "Read the raw HTTP response and answer.",
 "challenges": [
  {"q": "Server: Apache/2.4.49. What is notable?",
   "a": ["Apache is generally insecure", "2.4.49 has path traversal leading to RCE, CVE-2021-41773", "Should be nginx", "Nothing, it is current"],
   "c": 1, "why": "That exact version had a traversal that became remote code execution, and the header announced it."},
  {"q": "Set-Cookie: session=abc123; Path=/. What is missing?",
   "a": ["Secure and HttpOnly", "Domain", "Max-Age only", "Nothing"],
   "c": 0, "why": "Without Secure it travels in clear; without HttpOnly script can read it."},
  {"q": "Which header reveals the backend framework and version?",
   "a": ["Accept", "Server", "Content-Length", "Cache-Control"], "c": 1,
   "why": "Server frequently names the software and version."},
  {"q": "X-Powered-By: PHP/5.3.3. Action?",
   "a": ["Nothing", "An end of life PHP version is exposed, which is a finding in itself", "Upgrade Apache", "Add HTTPS"],
   "c": 1, "why": "5.3 is long unsupported, and telling the world is free reconnaissance."},
  {"q": "A 302 response to /admin with Location: /login means?",
   "a": ["Admin does not exist", "Admin exists but requires authentication", "Server error", "Rate limited"],
   "c": 1, "why": "The redirect to login confirms the endpoint is real behind an auth check."},
  {"q": "Access-Control-Allow-Origin reflecting your Origin with Allow-Credentials true means?",
   "a": ["Safe", "Any site can read authenticated responses for your session", "Required for APIs", "Only an issue on HTTP"],
   "c": 1, "why": "Credentials plus a reflected origin grants every site read access to your data."},
  {"q": "No X-Frame-Options and no CSP frame-ancestors means?",
   "a": ["Nothing", "The page can be framed, enabling clickjacking", "TLS is off", "Cookies leak"],
   "c": 1, "why": "Framing a page lets an attacker overlay it invisibly."},
  {"q": "Response has Cache-Control: public on /account with personal data. What is wrong?",
   "a": ["Nothing", "A shared cache may store and serve another user's private page", "It is slow", "TLS is needed"],
   "c": 1, "why": "Authenticated or personal responses must be private or no-store."},
 ],
}
